### ISSUE TITLE
Bind  items together with a bidirectional link

### ISSUE THREAD

**Issue by benel** [Hypertopic/Argos#58]
Related items existed in a prior version of Porphyry and Agorae (for the iSemantec project) whereas version 1 of the Hypertopic Protocol didn't specify it. The implementation was finally dropped when version 2 came out saying:

> Item-Item will remain unspecified until we have more real cases for it.
> Source: [Hypertopic Protocol Specification v2](https://github.com/Hypertopic/Protocol#requirements--design-choices)

The need for this feature emerges again among Porphyry contributors (see Hypertopic/Porphyry#188):

- as "suggested" by project "stained glasses" in 2019 and 2020 (@Hypertopic/visite-sur-site-de-vitraux),
-  as "suggested" by project "studying abroad" in 2020 (@Hypertopic/etudes-a-l-etranger),
- as "to do" by project "skills" in 2020 (@Hypertopic/approche-par-competences-de-la-formation).

Until it is specified in a future version of the protocol, this feature will be considered as "experimental" (formats and behaviours could change in the future).

The link will be stored in the item object which has the following format: 

```yaml
{
  "item_name": "N0", 
  "item_corpus": "C0", 
  "resource": "http://acme/bar", 
  "A": "V", 
  "topics": {
    "T1": {"viewpoint":"V1"}
  },
  "highlights": {
    "H": {
      "coordinates": [X,Y],
      "viewpoint": "V2",
      "topic": "T2"
    }
  }
}
```

 In order to be coherent with this format, it will be stored as: 
```yaml
  "items":{
    "I3": {"corpus": "C3"}
  },
```
where `I3` is the identifier and `C3` the corpus of the related item.

For now, the relation is unspecified (or équivalent to `related`), but it could be typed in an improved version.

In the item and corpus view. It will be added to the existing format:

```yaml
{"rows":[
  {"key":["C0","I0"], "value":{"name":"N2","resource":"http://acme/bar"}}, 
  {"key":["C0","I0"], "value":{"A":"V"}},
  {"key":["C0","I0"], "value":{"topic":{"viewpoint":"V1","id":"T1"}}},
  {"key":["C0","I0","H"], "value":{"coordinates":[X,Y], "topic":{"viewpoint":"V2", "id":"T2"}}}
]}
```
For coherence with `topic`, it could be:

```yaml
  {"key":["C0","I0"], "value":{"item":{"corpus":"C3","id":"I3"}}},
```

Please note that being bidirectional the link will also be displayed as:

```yaml
  {"key":["C3","I3"], "value":{"item":{"corpus":"C0","id":"I0"}}},
```

**Comment by benel** [comment]
Implementation tested on argos2.test.hypertopic.org:

* Extract of `/8a1750b17b11944108efaac593f4448e4e9f966b` (object):
```yaml
  "items": {
    "710a9531a5f6991321d3f27b637648c0cd5b7926": {
      "corpus": "Vitraux - Bénel"
    }
  }
```

* Extract of `/item/Vitraux%20-%20Bénel/8a1750b17b11944108efaac593f4448e4e9f966b` (view)

```yaml
    "key": ["Vitraux - Bénel", "8a1750b17b11944108efaac593f4448e4e9f966b"],
    "value": {
      (...)
      "item": [{
        "corpus": "Vitraux - Bénel",
        "id": "710a9531a5f6991321d3f27b637648c0cd5b7926"
      }],
      (...)
    }
```

* Extract of `/item/Vitraux%20-%20Bénel/710a9531a5f6991321d3f27b637648c0cd5b7926` (view)
```yaml
      "key": ["Vitraux - Bénel", "710a9531a5f6991321d3f27b637648c0cd5b7926"],
      "value": {
        "item": {
          "corpus": "Vitraux - Bénel",
          "id": "8a1750b17b11944108efaac593f4448e4e9f966b"
        }
      }
```
